### ISSUE TITLE
How should invalid terminations be handled.

### ISSUE THREAD

**Issue by Shashank-Shet** [Shashank-Shet/XOdia#7]
If the match does not terminate in the given number of iterations, (just as a last resort safeguard) the BM reports a DRAW. For winning and losing similar functionality will exist. But when an error occurs, who should be treated as a winner? Consider the following cases:
Error during process creation itself.
Termination before the first input is accepted. (Occurs rarely).

Inputs required.

**Comment by gdadlaney** [comment]
I think we should be in a position to decide whether the termination was because of the code or because of our system.

1) In the case of termination because to exceeding limits, it is counted as a loss, as the bot didn't handle the limits in their code.

2) If it is because of our system, we can declare the result as "Inconclusive" and restart the match. No points to either of the players.

In the above two cases, which category do they fit into? Do we have the codes which terminated in those cases?

**Comment by Shashank-Shet** [comment]
The errors you have stated, occur well into the match. In the current deployment, a bot was prone to termination right at the point of process invokation. The error was due to a lack of memory, the bot was a python bot. Should this be considered a loss

**Comment by gdadlaney** [comment]
I don't think it should. It is a failure of our system that memory was not allocated.

If this case can be fixed by respawning the process or restarting the match, that should be done, else the result should be Inconclusive

**Comment by Shashank-Shet** [comment]
That's the issue. The error went under the radar, and only extensive debugging identified the cause to be a memory error. The bot, when run independently is successful. But when called by the BM fails. Repeated respawning will yield the same outcome. So for this issue, the match can be held inconclusive, and aborted. But should this be different from a DRAW condition?

**Comment by gdadlaney** [comment]
A draw will award both players one point. Inconclusive will not award any points since it could have gone either way. It won't be counted as a valid match on the results page.

**Comment by Shashank-Shet** [comment]
Alright, so inconclusive matches will not award points. Will do.

**Comment by Shashank-Shet** [comment]
So the BM will terminate with the following error codes:
100 : draw
101: player1 win
102: player2 win
103: inconclusive match

Any changes?

**Comment by gdadlaney** [comment]
No, that's good
